apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-m74r
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-m74r
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-m74r
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-m74r
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-m74r
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-iwta-tenant/rhtap-demo-app/hacbs-test-project-m74r@sha256:739ea5b2f1e118aa7ee2649cdaf3ebfae39c6140c7296a0d8c695482ac67134f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
